// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// DGEMM
NumericMatrix DGEMM(SEXP xs, SEXP ys);
RcppExport SEXP RcppGLM_DGEMM(SEXP xsSEXP, SEXP ysSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ys(ysSEXP);
    __result = Rcpp::wrap(DGEMM(xs, ys));
    return __result;
END_RCPP
}
// DMM
NumericMatrix DMM(SEXP xs, SEXP ys);
RcppExport SEXP RcppGLM_DMM(SEXP xsSEXP, SEXP ysSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ys(ysSEXP);
    __result = Rcpp::wrap(DMM(xs, ys));
    return __result;
END_RCPP
}
// dgemm_blas
NumericMatrix dgemm_blas(NumericMatrix xs, NumericMatrix ys);
RcppExport SEXP RcppGLM_dgemm_blas(SEXP xsSEXP, SEXP ysSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ys(ysSEXP);
    __result = Rcpp::wrap(dgemm_blas(xs, ys));
    return __result;
END_RCPP
}
// dgeqr_lapack
NumericMatrix dgeqr_lapack(NumericMatrix x);
RcppExport SEXP RcppGLM_dgeqr_lapack(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    __result = Rcpp::wrap(dgeqr_lapack(x));
    return __result;
END_RCPP
}
// strassenMM
NumericMatrix strassenMM(SEXP xs, SEXP ys);
RcppExport SEXP RcppGLM_strassenMM(SEXP xsSEXP, SEXP ysSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ys(ysSEXP);
    __result = Rcpp::wrap(strassenMM(xs, ys));
    return __result;
END_RCPP
}
