# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title DGEMM
#' @param xs Matrix X
#' @param ys Matrix Y
#' @return zs Result Matrix Z
#' @export
DGEMM <- function(xs, ys) {
    .Call('RcppGLM_DGEMM', PACKAGE = 'RcppGLM', xs, ys)
}

#' @title DMM
#' @param xs Matrix X
#' @param ys Matrix Y
#' @return zs Result Matrix Z
#' @export
DMM <- function(xs, ys) {
    .Call('RcppGLM_DMM', PACKAGE = 'RcppGLM', xs, ys)
}

#' @title dgemm_blas
#' @param xs Matrix X
#' @param ys Matrix Y
#' @return zs Result Matrix Z
#' @export
dgemm_blas <- function(xs, ys) {
    .Call('RcppGLM_dgemm_blas', PACKAGE = 'RcppGLM', xs, ys)
}

#' @title dgeqr_lapack
#' @param x Matrix X to be
#' @return x
#' @export
dgeqr_lapack <- function(x) {
    .Call('RcppGLM_dgeqr_lapack', PACKAGE = 'RcppGLM', x)
}

#' @title strassenMM
#' @param xs Matrix x
#' @param ys Matrix y
#' @return zs Result Matrix
#' @export
strassenMM <- function(xs, ys) {
    .Call('RcppGLM_strassenMM', PACKAGE = 'RcppGLM', xs, ys)
}

